In [1]:
import pandas as pd
import json

In [2]:
df_matches = pd.read_csv("data/matches.csv")

In [3]:
df_matches.head(5)

,edition,round,score,team1,team2,url,venue,year
0,1930-URUGUAY,GROUP_STAGE,4-1 (3-0),France,Mexico (México),1930_URUGUAY_FS.htm#1-WC-30-I,Montevideo.,1930
1,1930-URUGUAY,GROUP_STAGE,3-0 (2-0),USA,Belgium (België),1930_URUGUAY_FS.htm#13-WC-30-I,Montevideo.,1930
2,1930-URUGUAY,GROUP_STAGE,2-1 (2-0),Yugoslavia (Југославија),Brazil (Brasil),1930_URUGUAY_FS.htm#7-WC-30-I,Montevideo.,1930
3,1930-URUGUAY,GROUP_STAGE,3-1 (1-0),Romania (România),Peru (Perú),1930_URUGUAY_FS.htm#10-WC-30-I,Montevideo.,1930
4,1930-URUGUAY,GROUP_STAGE,1-0 (0-0),Argentina,France,1930_URUGUAY_FS.htm#2-WC-30-I,Montevideo.,1930

In [4]:
WorldCup = pd.read_csv("data/WorldCup.csv", sep = ";")

In [5]:
WorldCup.head(5)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,2014,12 Jun 2014 - 17:00,Group A,Arena de Sao Paulo,Sao Paulo,Brazil,3,1,Croatia,,62103.0,1,1,NISHIMURA Yuichi (JPN),SAGARA Toru (JPN),NAGI Toshiyuki (JPN),255931,300186456,BRA,CRO
1,2014,13 Jun 2014 - 13:00,Group A,Estadio das Dunas,Natal,Mexico,1,0,Cameroon,,39216.0,0,0,ROLDAN Wilmar (COL),CLAVIJO Humberto (COL),DIAZ Eduardo (COL),255931,300186492,MEX,CMR
2,2014,13 Jun 2014 - 16:00,Group B,Arena Fonte Nova,Salvador,Spain,1,5,Netherlands,,48173.0,1,1,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255931,300186510,ESP,NED
3,2014,13 Jun 2014 - 18:00,Group B,Arena Pantanal,Cuiaba,Chile,3,1,Australia,,40275.0,2,1,Noumandiez DOUE (CIV),YEO Songuifolo (CIV),BIRUMUSHAHU Jean Claude (BDI),255931,300186473,CHI,AUS
4,2014,14 Jun 2014 - 13:00,Group C,Estadio Mineirao,Belo Horizonte,Colombia,3,0,Greece,,57174.0,1,0,GEIGER Mark (USA),HURD Sean (USA),FLETCHER Joe (CAN),255931,300186471,COL,GRE

In [7]:
with open("data/data_2018.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [8]:
import requests

In [9]:
data

{'stadiums': [{'id': 1,
   'name': 'Luzhniki Stadium',
   'city': 'Moscow',
   'lat': 55.715765,
   'lng': 37.5515217,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Luzhniki_Stadium%2C_Moscow.jpg'},
  {'id': 2,
   'name': 'Otkrytiye Arena',
   'city': 'Moscow',
   'lat': 55.817765,
   'lng': 37.440363,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/5/50/Stadium_Spartak_in_Moscow.jpg'},
  {'id': 3,
   'name': 'Krestovsky Stadium',
   'city': 'Saint Petersburg',
   'lat': 59.97274,
   'lng': 30.221408,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Spb_06-2017_img40_Krestovsky_Stadium.jpg'},
  {'id': 4,
   'name': 'Kaliningrad Stadium',
   'city': 'Kaliningrad',
   'lat': 54.698157,
   'lng': 20.533859,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Kaliningrad_stadium_-_2018-04-07.jpg'},
  {'id': 5,
   'name': 'Kazan Arena',
   'city': 'Kazan',
   'lat': 55.820983,
   'lng': 49.160966,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Kazan_Arena_08-2016.jpg'},
  {'id': 6,
   'name': 'Nizhny Novgorod Stadium',
   'city': 'Nizhny Novgorod',
   'lat': 56.337287,
   'lng': 43.963251,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/9/90/Nizhny_Novgorod_Stadium_%28March_2018%29.jpg'},
  {'id': 7,
   'name': 'Cosmos Arena',
   'city': 'Samara',
   'lat': 53.278146,
   'lng': 50.238854,
   'image': 'http://img.fifa.com/image/upload/t_l4/d0mymt1ubl2pypmu3gn3.jpg'},
  {'id': 8,
   'name': 'Volgograd Arena',
   'city': 'Volgograd',
   'lat': 48.734195,
   'lng': 44.548345,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/6/61/Construction_of_Volgograd_Arena_inside_04.jpg'},
  {'id': 9,
   'name': 'Mordovia Arena',
   'city': 'Saransk',
   'lat': 54.181795,
   'lng': 45.203851,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/4/45/Match_at_Mordovia_Arena_stadium.jpg'},
  {'id': 10,
   'name': 'Rostov Arena',
   'city': 'Rostov-on-Don',
   'lat': 47.209581,
   'lng': 39.738424,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/9/94/Rostov-Arens_%28april_2018%29_01.jpg'},
  {'id': 11,
   'name': 'Fisht Olympic Stadium',
   'city': 'Sochi',
   'lat': 43.402011,
   'lng': 39.955709,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/5/55/Fisht_Stadium_in_January_2018.jpg'},
  {'id': 12,
   'name': 'Central Stadium',
   'city': 'Yekaterinburg',
   'lat': 56.83249,
   'lng': 60.573585,
   'image': 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Estadio_Central_%28Ekaterinburg-arena%29.jpg'}],
 'tvchannels': [{'id': 1,
   'name': 'DR1',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/8/88/DR1_logo_2013.svg',
   'country': 'Denmark',
   'iso2': 'dk',
   'lang': ['da']},
  {'id': 2,
   'name': 'TV2',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/8/85/Danish_TV_2_logo.png',
   'country': 'Denmark',
   'iso2': 'dk',
   'lang': ['da']},
  {'id': 3,
   'name': 'BBC UK',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/e/eb/BBC.svg',
   'country': 'UK',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 4,
   'name': 'ITV UK',
   'icon': 'https://upload.wikimedia.org/wikipedia/en/9/92/ITV_logo_2013.svg',
   'country': 'UK',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 5,
   'name': 'ITV4 UK',
   'icon': 'https://upload.wikimedia.org/wikipedia/en/9/92/ITV_logo_2013.svg',
   'country': 'UK',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 6,
   'name': 'Cuatro',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/f/f8/Logotipo_de_Cuatro.svg',
   'country': 'Spain',
   'iso2': 'es',
   'lang': ['es']},
  {'id': 7,
   'name': 'Telecinco',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/7/75/Telecinco_2012.png',
   'country': 'Spain',
   'iso2': 'es',
   'lang': ['es']},
  {'id': 8,
   'name': 'Globo',
   'icon': 'https://upload.wikimedia.org/wikipedia/pt/2/22/Logotipo_da_Rede_Globo.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 9,
   'name': 'SportTV',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/SporTV_2017_logo.svg/692px-SporTV_2017_logo.svg.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 10,
   'name': 'SportTV2',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/SporTV_2_2017_logo.svg/664px-SporTV_2_2017_logo.svg.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 11,
   'name': 'SportTV3',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/SporTV_3_2017_logo.svg/703px-SporTV_3_2017_logo.svg.png',
   'country': 'Brazil',
   'iso2': 'br',
   'lang': ['pt-br']},
  {'id': 12,
   'name': 'Sony Ten',
   'icon': 'https://upload.wikimedia.org/wikipedia/en/5/5f/Sony_TEN_logo.png',
   'country': 'India',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 13,
   'name': 'Fox',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/2/25/FOX_wordmark.svg',
   'country': 'USA',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 14,
   'name': 'FS1',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/3/37/2015_Fox_Sports_1_logo.svg',
   'country': 'USA',
   'iso2': 'en',
   'lang': ['en']},
  {'id': 15,
   'name': 'TransTV',
   'icon': 'https://upload.wikimedia.org/wikipedia/id/6/62/Trans_TV_2013.svg',
   'country': 'Indonesia',
   'iso2': 'id',
   'lang': ['id']},
  {'id': 16,
   'name': 'Trans7',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Trans_7_2013_Iklan.svg',
   'country': 'Indonesia',
   'iso2': 'id',
   'lang': ['id']},
  {'id': 17,
   'name': 'ARD',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/6/68/ARD_logo.svg',
   'country': 'Germany',
   'iso2': 'de',
   'lang': ['de']},
  {'id': 18,
   'name': 'ZDF',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/c/c1/ZDF_logo.svg',
   'country': 'Germany',
   'iso2': 'de',
   'lang': ['de']},
  {'id': 19,
   'name': 'ONE',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/1/16/One_TV_Logo.svg',
   'country': 'Germany',
   'iso2': 'de',
   'lang': ['de']},
  {'id': 20,
   'name': 'TVP 1',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/TVP1_logo.svg/2000px-TVP1_logo.svg.png',
   'country': 'Poland',
   'iso2': 'pl',
   'lang': ['pl']},
  {'id': 21,
   'name': 'TVP 2',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/TVP2_logo.svg/2000px-TVP2_logo.svg.png',
   'country': 'Poland',
   'iso2': 'pl',
   'lang': ['pl']},
  {'id': 22,
   'name': 'TVP SPORT',
   'icon': 'https://upload.wikimedia.org/wikipedia/commons/7/76/NewTVP_SPORT.png',
   'country': 'Poland',
   'iso2': 'pl',
   'lang': ['pl']}],
 'teams': [{'id': 1,
   'name': 'Russia',
   'fifaCode': 'RUS',
   'iso2': 'ru',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/900px-Flag_of_Russia.png',
   'emoji': 'flag-ru',
   'emojiString': '🇷🇺'},
  {'id': 2,
   'name': 'Saudi Arabia',
   'fifaCode': 'KSA',
   'iso2': 'sa',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/750px-Flag_of_Saudi_Arabia.png',
   'emoji': 'flag-sa',
   'emojiString': '🇸🇦'},
  {'id': 3,
   'name': 'Egypt',
   'fifaCode': 'EGY',
   'iso2': 'eg',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/900px-Flag_of_Egypt.png',
   'emoji': 'flag-eg',
   'emojiString': '🇪🇬'},
  {'id': 4,
   'name': 'Uruguay',
   'fifaCode': 'URU',
   'iso2': 'uy',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/900px-Flag_of_Uruguay.png',
   'emoji': 'flag-uy',
   'emojiString': '🇺🇾'},
  {'id': 5,
   'name': 'Portugal',
   'fifaCode': 'POR',
   'iso2': 'pt',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/600px-Flag_of_Portugal.png',
   'emoji': 'flag-pt',
   'emojiString': '🇵🇹'},
  {'id': 6,
   'name': 'Spain',
   'fifaCode': 'ESP',
   'iso2': 'es',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/750px-Flag_of_Spain.png',
   'emoji': 'flag-es',
   'emojiString': '🇪🇸'},
  {'id': 7,
   'name': 'Morocco',
   'fifaCode': 'MAR',
   'iso2': 'ma',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/900px-Flag_of_Morocco.png',
   'emoji': 'flag-ma',
   'emojiString': '🇲🇦'},
  {'id': 8,
   'name': 'Iran',
   'fifaCode': 'IRN',
   'iso2': 'ir',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/630px-Flag_of_Iran.png',
   'emoji': 'flag-ir',
   'emojiString': '🇮🇷'},
  {'id': 9,
   'name': 'France',
   'fifaCode': 'FRA',
   'iso2': 'fr',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/900px-Flag_of_France.png',
   'emoji': 'flag-fr',
   'emojiString': '🇫🇷'},
  {'id': 10,
   'name': 'Australia',
   'fifaCode': 'AUS',
   'iso2': 'au',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/1280px-Flag_of_Australia_%28converted%29.png',
   'emoji': 'flag-au',
   'emojiString': '🇦🇺'},
  {'id': 11,
   'name': 'Peru',
   'fifaCode': 'PER',
   'iso2': 'pe',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Peru_%28state%29.svg/900px-Flag_of_Peru_%28state%29.png',
   'emoji': 'flag-pe',
   'emojiString': '🇵🇪'},
  {'id': 12,
   'name': 'Denmark',
   'fifaCode': 'DEN',
   'iso2': 'dk',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/740px-Flag_of_Denmark.png',
   'emoji': 'flag-dk',
   'emojiString': '🇩🇰'},
  {'id': 13,
   'name': 'Argentina',
   'fifaCode': 'ARG',
   'iso2': 'ar',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/800px-Flag_of_Argentina.png',
   'emoji': 'flag-ar',
   'emojiString': '🇦🇷'},
  {'id': 14,
   'name': 'Iceland',
   'fifaCode': 'ISL',
   'iso2': 'is',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/800px-Flag_of_Iceland.png',
   'emoji': 'flag-is',
   'emojiString': '🇮🇸'},
  {'id': 15,
   'name': 'Croatia',
   'fifaCode': 'CRO',
   'iso2': 'hr',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/800px-Flag_of_Croatia.png',
   'emoji': 'flag-hr',
   'emojiString': '🇭🇷'},
  {'id': 16,
   'name': 'Nigeria',
   'fifaCode': 'NGA',
   'iso2': 'ng',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/800px-Flag_of_Nigeria.png',
   'emoji': 'flag-ng',
   'emojiString': '🇳🇬'},
  {'id': 17,
   'name': 'Brazil',
   'fifaCode': 'BRA',
   'iso2': 'br',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/720px-Flag_of_Brazil.png',
   'emoji': 'flag-br',
   'emojiString': '🇧🇷'},
  {'id': 18,
   'name': 'Switzerland',
   'fifaCode': 'SUI',
   'iso2': 'ch',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/320px-Flag_of_Switzerland_%28Pantone%29.png',
   'emoji': 'flag-ch',
   'emojiString': '🇨🇭'},
  {'id': 19,
   'name': 'Costa Rica',
   'fifaCode': 'CRC',
   'iso2': 'cr',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/833px-Flag_of_Costa_Rica_%28state%29.png',
   'emoji': 'flag-cr',
   'emojiString': '🇨🇷'},
  {'id': 20,
   'name': 'Serbia',
   'fifaCode': 'SRB',
   'iso2': 'rs',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1350px-Flag_of_Serbia.png',
   'emoji': 'flag-rs',
   'emojiString': '🇷🇸'},
  {'id': 21,
   'name': 'Germany',
   'fifaCode': 'GER',
   'iso2': 'de',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/800px-Flag_of_Germany.png',
   'emoji': 'flag-de',
   'emojiString': '🇩🇪'},
  {'id': 22,
   'name': 'Mexico',
   'fifaCode': 'MEX',
   'iso2': 'mx',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/800px-Flag_of_Mexico.png',
   'emoji': 'flag-mx',
   'emojiString': '🇲🇽'},
  {'id': 23,
   'name': 'Sweden',
   'fifaCode': 'SWE',
   'iso2': 'se',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/1600px-Flag_of_Sweden.png',
   'emoji': 'flag-se',
   'emojiString': '🇸🇪'},
  {'id': 24,
   'name': 'South Korea',
   'fifaCode': 'KOR',
   'iso2': 'kr',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/900px-Flag_of_South_Korea.png',
   'emoji': 'flag-kr',
   'emojiString': '🇰🇷'},
  {'id': 25,
   'name': 'Belgium',
   'fifaCode': 'BEL',
   'iso2': 'be',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/450px-Flag_of_Belgium.png',
   'emoji': 'flag-be',
   'emojiString': '🇧🇪'},
  {'id': 26,
   'name': 'Panama',
   'fifaCode': 'PAN',
   'iso2': 'pa',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/450px-Flag_of_Panama.png',
   'emoji': 'flag-pa',
   'emojiString': '🇵🇦'},
  {'id': 27,
   'name': 'Tunisia',
   'fifaCode': 'TUN',
   'iso2': 'tn',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1200px-Flag_of_Tunisia.png',
   'emoji': 'flag-tn',
   'emojiString': '🇹🇳'},
  {'id': 28,
   'name': 'England',
   'fifaCode': 'ENG',
   'iso2': 'gb-eng',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/800px-Flag_of_England.png',
   'emoji': 'flag-england',
   'emojiString': '🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f'},
  {'id': 29,
   'name': 'Poland',
   'fifaCode': 'POL',
   'iso2': 'pl',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/1280px-Flag_of_Poland.png',
   'emoji': 'flag-pl',
   'emojiString': '🇵🇱'},
  {'id': 30,
   'name': 'Senegal',
   'fifaCode': 'SEN',
   'iso2': 'sn',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/900px-Flag_of_Senegal.svg.png',
   'emoji': 'flag-sn',
   'emojiString': '🇸🇳'},
  {'id': 31,
   'name': 'Colombia',
   'fifaCode': 'COL',
   'iso2': 'co',
   'flag': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/450px-Flag_of_Colombia.png',
   'emoji': 'flag-co',
   'emojiString': '🇨🇴'},
  {'id': 32,
   'name': 'Japan',
   'fifaCode': 'JPN',
   'iso2': 'jp',
   'flag': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/900px-Flag_of_Japan.png',
   'emoji': 'flag-jp',
   'emojiString': '🇯🇵'}],
 'groups': {'a': {'name': 'Group A',
   'winner': 4,
   'runnerup': 1,
   'matches': [{'name': 1,
     'type': 'group',
     'home_team': 1,
     'away_team': 2,
     'home_result': 5,
     'away_result': 0,
     'date': '2018-06-14T18:00:00+03:00',
     'stadium': 1,
     'channels': [4, 6, 13, 17, 20, 22],
     'finished': True,
     'matchday': 1},
    {'name': 2,
     'type': 'group',
     'home_team': 3,
     'away_team': 4,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-15T17:00:00+05:00',
     'stadium': 12,
     'channels': [3, 6, 14, 17, 20, 22],
     'finished': True,
     'matchday': 1},
    {'name': 17,
     'type': 'group',
     'home_team': 1,
     'away_team': 3,
     'home_result': 3,
     'away_result': 1,
     'date': '2018-06-19T21:00:00+03:00',
     'stadium': 3,
     'channels': [3, 6, 13, 17, 15, 21, 22],
     'finished': True,
     'matchday': 2},
    {'name': 18,
     'type': 'group',
     'home_team': 4,
     'away_team': 2,
     'home_result': 1,
     'away_result': 0,
     'date': '2018-06-20T18:00:00+03:00',
     'stadium': 10,
     'channels': [3, 6, 13, 17, 21, 22],
     'finished': True,
     'matchday': 2},
    {'name': 33,
     'type': 'group',
     'home_team': 4,
     'away_team': 1,
     'home_result': 3,
     'away_result': 0,
     'date': '2018-06-25T18:00:00+04:00',
     'stadium': 7,
     'channels': [4, 6, 13, 18, 15, 20, 22],
     'finished': True,
     'matchday': 3},
    {'name': 34,
     'type': 'group',
     'home_team': 2,
     'away_team': 3,
     'home_result': 2,
     'away_result': 1,
     'date': '2018-06-25T17:00:00+03:00',
     'stadium': 8,
     'channels': [5, 6, 14, 18, 15, 21, 22],
     'finished': True,
     'matchday': 3}]},
  'b': {'name': 'Group B',
   'winner': 6,
   'runnerup': 5,
   'matches': [{'name': 3,
     'type': 'group',
     'home_team': 5,
     'away_team': 6,
     'home_result': 3,
     'away_result': 3,
     'date': '2018-06-15T21:00:00+03:00',
     'stadium': 11,
     'channels': [3, 7, 13, 15, 17, 20, 22],
     'finished': True,
     'matchday': 1},
    {'name': 4,
     'type': 'group',
     'home_team': 7,
     'away_team': 8,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-15T18:00:00+03:00',
     'stadium': 3,
     'channels': [4, 6, 13, 17, 21, 22],
     'finished': True,
     'matchday': 1},
    {'name': 19,
     'type': 'group',
     'home_team': 5,
     'away_team': 7,
     'home_result': 1,
     'away_result': 0,
     'date': '2018-06-20T15:00:00+03:00',
     'stadium': 1,
     'channels': [3, 6, 14, 15, 17, 20, 22],
     'finished': True,
     'matchday': 2},
    {'name': 20,
     'type': 'group',
     'home_team': 8,
     'away_team': 6,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-20T21:00:00+03:00',
     'stadium': 5,
     'channels': [4, 7, 13, 15, 17, 20, 21],
     'finished': True,
     'matchday': 2},
    {'name': 35,
     'type': 'group',
     'home_team': 8,
     'away_team': 5,
     'home_result': 1,
     'away_result': 1,
     'date': '2018-06-25T21:00:00+03:00',
     'stadium': 9,
     'channels': [3, 6, 13, 18, 21, 22],
     'finished': True,
     'matchday': 3},
    {'name': 36,
     'type': 'group',
     'home_team': 6,
     'away_team': 7,
     'home_result': 2,
     'away_result': 2,
     'date': '2018-06-25T20:00:00+02:00',
     'stadium': 4,
     'channels': [3, 7, 14, 18, 21, 22],
     'finished': True,
     'matchday': 3}]},
  'c': {'name': 'Group C',
   'winner': 9,
   'runnerup': 12,
   'matches': [{'name': 5,
     'type': 'group',
     'home_team': 9,
     'away_team': 10,
     'home_result': 2,
     'away_result': 1,
     'date': '2018-06-16T13:00:00+03:00',
     'stadium': 5,
     'channels': [3, 6, 14, 15, 18, 21, 22],
     'finished': True,
     'matchday': 1},
    {'name': 6,
     'type': 'group',
     'home_team': 11,
     'away_team': 12,
     'home_result': 0,
     'away_result': 1,
     'date': '2018-06-16T19:00:00+03:00',
     'stadium': 9,
     'channels': [3, 6, 14, 15, 18, 21, 22],
     'finished': True,
     'matchday': 1},
    {'name': 21,
     'type': 'group',
     'home_team': 9,
     'away_team': 11,
     'home_result': 1,
     'away_result': 0,
     'date': '2018-06-21T20:00:00+05:00',
     'stadium': 12,
     'channels': [4, 6, 13, 15, 18, 21, 22],
     'finished': True,
     'matchday': 2},
    {'name': 22,
     'type': 'group',
     'home_team': 12,
     'away_team': 10,
     'home_result': 1,
     'away_result': 1,
     'date': '2018-06-21T16:00:00+04:00',
     'stadium': 7,
     'channels': [4, 6, 14, 15, 18, 20, 22],
     'finished': True,
     'matchday': 2},
    {'name': 37,
     'type': 'group',
     'home_team': 12,
     'away_team': 9,
     'home_result': 0,
     'away_result': 0,
     'date': '2018-06-26T17:00:00+03:00',
     'stadium': 1,
     'channels': [4, 6, 13, 15, 17, 20, 22],
     'finished': True,
     'matchday': 3},
    {'name': 38,
     'type': 'group',
     'home_team': 10,
     'away_team': 11,
     'home_result': 0,
     'away_result': 2,
     'date': '2018-06-26T17:00:00+03:00',
     'stadium': 11,
     'channels': [5, 6, 14, 16, 19, 21, 22],
     'finished': True,
     'matchday': 3}]},
  'd': {'name': 'Group D',
   'winner': 15,
   'runnerup': 13,
   'matches': [{'name': 7,
     'type': 'group',
     'home_team': 13,
     'away_team': 14,
     'home_result': 1,
     'away_result': 1,
     'date': '2018-06-16T16:00:00+03:00',
     'stadium': 2,
     'channels': [4, 6, 13, 18, 20, 22],

In [10]:
url = "https://worldcupjson.net/matches"
response = requests.get(url)
test = response.json()
test

[{'id': 1,
  'venue': 'Al Bayt Stadium',
  'location': 'Al Khor',
  'status': 'completed',
  'attendance': '67372',
  'stage_name': 'First stage',
  'home_team_country': 'QAT',
  'away_team_country': 'ECU',
  'datetime': '2022-11-20T16:00:00Z',
  'winner': 'Ecuador',
  'winner_code': 'ECU',
  'home_team': {'country': 'QAT', 'name': 'Qatar', 'goals': 0, 'penalties': 0},
  'away_team': {'country': 'ECU',
   'name': 'Ecuador',
   'goals': 2,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:03Z',
  'last_changed_at': '2023-01-01T10:16:03Z'},
 {'id': 2,
  'venue': 'Khalifa International Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '45334',
  'stage_name': 'First stage',
  'home_team_country': 'ENG',
  'away_team_country': 'IRN',
  'datetime': '2022-11-21T13:00:00Z',
  'winner': 'England',
  'winner_code': 'ENG',
  'home_team': {'country': 'ENG',
   'name': 'England',
   'goals': 6,
   'penalties': 0},
  'away_team': {'country': 'IRN', 'name': 'Iran', 'goals': 2, 'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 3,
  'venue': 'Al Thumama Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '41721',
  'stage_name': 'First stage',
  'home_team_country': 'SEN',
  'away_team_country': 'NED',
  'datetime': '2022-11-21T16:00:00Z',
  'winner': 'Netherlands',
  'winner_code': 'NED',
  'home_team': {'country': 'SEN',
   'name': 'Senegal',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'NED',
   'name': 'Netherlands',
   'goals': 2,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 4,
  'venue': 'Ahmad Bin Ali Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '43418',
  'stage_name': 'First stage',
  'home_team_country': 'USA',
  'away_team_country': 'WAL',
  'datetime': '2022-11-21T19:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'USA',
   'name': 'United States',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'WAL', 'name': 'Wales', 'goals': 1, 'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:22Z',
  'last_changed_at': '2023-01-01T10:53:22Z'},
 {'id': 5,
  'venue': 'Lusail Stadium',
  'location': 'Al Daayen',
  'status': 'completed',
  'attendance': '88012',
  'stage_name': 'First stage',
  'home_team_country': 'ARG',
  'away_team_country': 'KSA',
  'datetime': '2022-11-22T10:00:00Z',
  'winner': 'Saudi Arabia',
  'winner_code': 'KSA',
  'home_team': {'country': 'ARG',
   'name': 'Argentina',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'KSA',
   'name': 'Saudi Arabia',
   'goals': 2,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 6,
  'venue': 'Education City Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '42925',
  'stage_name': 'First stage',
  'home_team_country': 'DEN',
  'away_team_country': 'TUN',
  'datetime': '2022-11-22T13:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'DEN',
   'name': 'Denmark',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'TUN',
   'name': 'Tunisia',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:06Z',
  'last_changed_at': '2023-01-01T10:53:06Z'},
 {'id': 7,
  'venue': 'Stadium 974',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '39369',
  'stage_name': 'First stage',
  'home_team_country': 'MEX',
  'away_team_country': 'POL',
  'datetime': '2022-11-22T16:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'MEX',
   'name': 'Mexico',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'POL',
   'name': 'Poland',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:13Z',
  'last_changed_at': '2023-01-01T10:53:13Z'},
 {'id': 8,
  'venue': 'Al Janoub Stadium',
  'location': 'Al Wakrah',
  'status': 'completed',
  'attendance': '40875',
  'stage_name': 'First stage',
  'home_team_country': 'FRA',
  'away_team_country': 'AUS',
  'datetime': '2022-11-22T19:00:00Z',
  'winner': 'France',
  'winner_code': 'FRA',
  'home_team': {'country': 'FRA',
   'name': 'France',
   'goals': 4,
   'penalties': 0},
  'away_team': {'country': 'AUS',
   'name': 'Australia',
   'goals': 1,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 9,
  'venue': 'Al Bayt Stadium',
  'location': 'Al Khor',
  'status': 'completed',
  'attendance': '59407',
  'stage_name': 'First stage',
  'home_team_country': 'MAR',
  'away_team_country': 'CRO',
  'datetime': '2022-11-23T10:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'MAR',
   'name': 'Morocco',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'CRO',
   'name': 'Croatia',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:20Z',
  'last_changed_at': '2023-01-01T10:53:20Z'},
 {'id': 10,
  'venue': 'Khalifa International Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '42608',
  'stage_name': 'First stage',
  'home_team_country': 'GER',
  'away_team_country': 'JPN',
  'datetime': '2022-11-23T13:00:00Z',
  'winner': 'Japan',
  'winner_code': 'JPN',
  'home_team': {'country': 'GER',
   'name': 'Germany',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'JPN', 'name': 'Japan', 'goals': 2, 'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 11,
  'venue': 'Al Thumama Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '40013',
  'stage_name': 'First stage',
  'home_team_country': 'ESP',
  'away_team_country': 'CRC',
  'datetime': '2022-11-23T16:00:00Z',
  'winner': 'Spain',
  'winner_code': 'ESP',
  'home_team': {'country': 'ESP', 'name': 'Spain', 'goals': 7, 'penalties': 0},
  'away_team': {'country': 'CRC',
   'name': 'Costa Rica',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:03Z',
  'last_changed_at': '2023-01-01T10:16:03Z'},
 {'id': 12,
  'venue': 'Ahmad Bin Ali Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '40432',
  'stage_name': 'First stage',
  'home_team_country': 'BEL',
  'away_team_country': 'CAN',
  'datetime': '2022-11-23T19:00:00Z',
  'winner': 'Belgium',
  'winner_code': 'BEL',
  'home_team': {'country': 'BEL',
   'name': 'Belgium',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'CAN',
   'name': 'Canada',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:03Z',
  'last_changed_at': '2023-01-01T10:16:03Z'},
 {'id': 13,
  'venue': 'Al Janoub Stadium',
  'location': 'Al Wakrah',
  'status': 'completed',
  'attendance': '39089',
  'stage_name': 'First stage',
  'home_team_country': 'SUI',
  'away_team_country': 'CMR',
  'datetime': '2022-11-24T10:00:00Z',
  'winner': 'Switzerland',
  'winner_code': 'SUI',
  'home_team': {'country': 'SUI',
   'name': 'Switzerland',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'CMR',
   'name': 'Cameroon',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 14,
  'venue': 'Education City Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '41663',
  'stage_name': 'First stage',
  'home_team_country': 'URU',
  'away_team_country': 'KOR',
  'datetime': '2022-11-24T13:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'URU',
   'name': 'Uruguay',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'KOR',
   'name': 'Korea Republic',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:02Z',
  'last_changed_at': '2023-01-01T10:53:02Z'},
 {'id': 15,
  'venue': 'Stadium 974',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '42662',
  'stage_name': 'First stage',
  'home_team_country': 'POR',
  'away_team_country': 'GHA',
  'datetime': '2022-11-24T16:00:00Z',
  'winner': 'Portugal',
  'winner_code': 'POR',
  'home_team': {'country': 'POR',
   'name': 'Portugal',
   'goals': 3,
   'penalties': 0},
  'away_team': {'country': 'GHA', 'name': 'Ghana', 'goals': 2, 'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 16,
  'venue': 'Lusail Stadium',
  'location': 'Al Daayen',
  'status': 'completed',
  'attendance': '88103',
  'stage_name': 'First stage',
  'home_team_country': 'BRA',
  'away_team_country': 'SRB',
  'datetime': '2022-11-24T19:00:00Z',
  'winner': 'Brazil',
  'winner_code': 'BRA',
  'home_team': {'country': 'BRA',
   'name': 'Brazil',
   'goals': 2,
   'penalties': 0},
  'away_team': {'country': 'SRB',
   'name': 'Serbia',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 17,
  'venue': 'Ahmad Bin Ali Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '40875',
  'stage_name': 'First stage',
  'home_team_country': 'WAL',
  'away_team_country': 'IRN',
  'datetime': '2022-11-25T10:00:00Z',
  'winner': 'Iran',
  'winner_code': 'IRN',
  'home_team': {'country': 'WAL', 'name': 'Wales', 'goals': 0, 'penalties': 0},
  'away_team': {'country': 'IRN', 'name': 'Iran', 'goals': 2, 'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 18,
  'venue': 'Al Thumama Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '41797',
  'stage_name': 'First stage',
  'home_team_country': 'QAT',
  'away_team_country': 'SEN',
  'datetime': '2022-11-25T13:00:00Z',
  'winner': 'Senegal',
  'winner_code': 'SEN',
  'home_team': {'country': 'QAT', 'name': 'Qatar', 'goals': 1, 'penalties': 0},
  'away_team': {'country': 'SEN',
   'name': 'Senegal',
   'goals': 3,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 19,
  'venue': 'Khalifa International Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '44833',
  'stage_name': 'First stage',
  'home_team_country': 'NED',
  'away_team_country': 'ECU',
  'datetime': '2022-11-25T16:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'NED',
   'name': 'Netherlands',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'ECU',
   'name': 'Ecuador',
   'goals': 1,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:11Z',
  'last_changed_at': '2023-01-01T10:53:11Z'},
 {'id': 20,
  'venue': 'Al Bayt Stadium',
  'location': 'Al Khor',
  'status': 'completed',
  'attendance': '68463',
  'stage_name': 'First stage',
  'home_team_country': 'ENG',
  'away_team_country': 'USA',
  'datetime': '2022-11-25T19:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'ENG',
   'name': 'England',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'USA',
   'name': 'United States',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:04Z',
  'last_changed_at': '2023-01-01T10:53:04Z'},
 {'id': 21,
  'venue': 'Al Janoub Stadium',
  'location': 'Al Wakrah',
  'status': 'completed',
  'attendance': '41823',
  'stage_name': 'First stage',
  'home_team_country': 'TUN',
  'away_team_country': 'AUS',
  'datetime': '2022-11-26T10:00:00Z',
  'winner': 'Australia',
  'winner_code': 'AUS',
  'home_team': {'country': 'TUN',
   'name': 'Tunisia',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'AUS',
   'name': 'Australia',
   'goals': 1,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 22,
  'venue': 'Education City Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '44259',
  'stage_name': 'First stage',
  'home_team_country': 'POL',
  'away_team_country': 'KSA',
  'datetime': '2022-11-26T13:00:00Z',
  'winner': 'Poland',
  'winner_code': 'POL',
  'home_team': {'country': 'POL',
   'name': 'Poland',
   'goals': 2,
   'penalties': 0},
  'away_team': {'country': 'KSA',
   'name': 'Saudi Arabia',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 23,
  'venue': 'Stadium 974',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '42860',
  'stage_name': 'First stage',
  'home_team_country': 'FRA',
  'away_team_country': 'DEN',
  'datetime': '2022-11-26T16:00:00Z',
  'winner': 'France',
  'winner_code': 'FRA',
  'home_team': {'country': 'FRA',
   'name': 'France',
   'goals': 2,
   'penalties': 0},
  'away_team': {'country': 'DEN',
   'name': 'Denmark',
   'goals': 1,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:00Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 24,
  'venue': 'Lusail Stadium',
  'location': 'Al Daayen',
  'status': 'completed',
  'attendance': '88966',
  'stage_name': 'First stage',
  'home_team_country': 'ARG',
  'away_team_country': 'MEX',
  'datetime': '2022-11-26T19:00:00Z',
  'winner': 'Argentina',
  'winner_code': 'ARG',
  'home_team': {'country': 'ARG',
   'name': 'Argentina',
   'goals': 2,
   'penalties': 0},
  'away_team': {'country': 'MEX',
   'name': 'Mexico',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 25,
  'venue': 'Ahmad Bin Ali Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '41479',
  'stage_name': 'First stage',
  'home_team_country': 'JPN',
  'away_team_country': 'CRC',
  'datetime': '2022-11-27T10:00:00Z',
  'winner': 'Costa Rica',
  'winner_code': 'CRC',
  'home_team': {'country': 'JPN', 'name': 'Japan', 'goals': 0, 'penalties': 0},
  'away_team': {'country': 'CRC',
   'name': 'Costa Rica',
   'goals': 1,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 26,
  'venue': 'Al Thumama Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '43738',
  'stage_name': 'First stage',
  'home_team_country': 'BEL',
  'away_team_country': 'MAR',
  'datetime': '2022-11-27T13:00:00Z',
  'winner': 'Morocco',
  'winner_code': 'MAR',
  'home_team': {'country': 'BEL',
   'name': 'Belgium',
   'goals': 0,
   'penalties': 0},
  'away_team': {'country': 'MAR',
   'name': 'Morocco',
   'goals': 2,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 27,
  'venue': 'Khalifa International Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '44374',
  'stage_name': 'First stage',
  'home_team_country': 'CRO',
  'away_team_country': 'CAN',
  'datetime': '2022-11-27T16:00:00Z',
  'winner': 'Croatia',
  'winner_code': 'CRO',
  'home_team': {'country': 'CRO',
   'name': 'Croatia',
   'goals': 4,
   'penalties': 0},
  'away_team': {'country': 'CAN',
   'name': 'Canada',
   'goals': 1,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:02Z',
  'last_changed_at': '2023-01-01T10:16:02Z'},
 {'id': 28,
  'venue': 'Al Bayt Stadium',
  'location': 'Al Khor',
  'status': 'completed',
  'attendance': '68895',
  'stage_name': 'First stage',
  'home_team_country': 'ESP',
  'away_team_country': 'GER',
  'datetime': '2022-11-27T19:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'ESP', 'name': 'Spain', 'goals': 1, 'penalties': 0},
  'away_team': {'country': 'GER',
   'name': 'Germany',
   'goals': 1,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:15Z',
  'last_changed_at': '2023-01-01T10:53:15Z'},
 {'id': 29,
  'venue': 'Al Janoub Stadium',
  'location': 'Al Wakrah',
  'status': 'completed',
  'attendance': '39789',
  'stage_name': 'First stage',
  'home_team_country': 'CMR',
  'away_team_country': 'SRB',
  'datetime': '2022-11-28T10:00:00Z',
  'winner': 'Draw',
  'winner_code': 'Draw',
  'home_team': {'country': 'CMR',
   'name': 'Cameroon',
   'goals': 3,
   'penalties': 0},
  'away_team': {'country': 'SRB',
   'name': 'Serbia',
   'goals': 3,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:53:18Z',
  'last_changed_at': '2023-01-01T10:53:18Z'},
 {'id': 30,
  'venue': 'Education City Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '43983',
  'stage_name': 'First stage',
  'home_team_country': 'KOR',
  'away_team_country': 'GHA',
  'datetime': '2022-11-28T13:00:00Z',
  'winner': 'Ghana',
  'winner_code': 'GHA',
  'home_team': {'country': 'KOR',
   'name': 'Korea Republic',
   'goals': 2,
   'penalties': 0},
  'away_team': {'country': 'GHA', 'name': 'Ghana', 'goals': 3, 'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 31,
  'venue': 'Stadium 974',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '43649',
  'stage_name': 'First stage',
  'home_team_country': 'BRA',
  'away_team_country': 'SUI',
  'datetime': '2022-11-28T16:00:00Z',
  'winner': 'Brazil',
  'winner_code': 'BRA',
  'home_team': {'country': 'BRA',
   'name': 'Brazil',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'SUI',
   'name': 'Switzerland',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 32,
  'venue': 'Lusail Stadium',
  'location': 'Al Daayen',
  'status': 'completed',
  'attendance': '88668',
  'stage_name': 'First stage',
  'home_team_country': 'POR',
  'away_team_country': 'URU',
  'datetime': '2022-11-28T19:00:00Z',
  'winner': 'Portugal',
  'winner_code': 'POR',
  'home_team': {'country': 'POR',
   'name': 'Portugal',
   'goals': 2,
   'penalties': 0},
  'away_team': {'country': 'URU',
   'name': 'Uruguay',
   'goals': 0,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 33,
  'venue': 'Al Bayt Stadium',
  'location': 'Al Khor',
  'status': 'completed',
  'attendance': '66784',
  'stage_name': 'First stage',
  'home_team_country': 'NED',
  'away_team_country': 'QAT',
  'datetime': '2022-11-29T15:00:00Z',
  'winner': 'Netherlands',
  'winner_code': 'NED',
  'home_team': {'country': 'NED',
   'name': 'Netherlands',
   'goals': 2,
   'penalties': 0},
  'away_team': {'country': 'QAT', 'name': 'Qatar', 'goals': 0, 'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 34,
  'venue': 'Khalifa International Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '44569',
  'stage_name': 'First stage',
  'home_team_country': 'ECU',
  'away_team_country': 'SEN',
  'datetime': '2022-11-29T15:00:00Z',
  'winner': 'Senegal',
  'winner_code': 'SEN',
  'home_team': {'country': 'ECU',
   'name': 'Ecuador',
   'goals': 1,
   'penalties': 0},
  'away_team': {'country': 'SEN',
   'name': 'Senegal',
   'goals': 2,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 35,
  'venue': 'Ahmad Bin Ali Stadium',
  'location': 'Ar-Rayyan',
  'status': 'completed',
  'attendance': '44297',
  'stage_name': 'First stage',
  'home_team_country': 'WAL',
  'away_team_country': 'ENG',
  'datetime': '2022-11-29T19:00:00Z',
  'winner': 'England',
  'winner_code': 'ENG',
  'home_team': {'country': 'WAL', 'name': 'Wales', 'goals': 0, 'penalties': 0},
  'away_team': {'country': 'ENG',
   'name': 'England',
   'goals': 3,
   'penalties': 0},
  'last_checked_at': '2023-01-01T10:16:01Z',
  'last_changed_at': '2023-01-01T10:16:01Z'},
 {'id': 36,
  'venue': 'Al Thumama Stadium',
  'location': 'Doha',
  'status': 'completed',
  'attendance': '42127',
  'stage_name': 'First stage',